proyek/blog/urls.py
from django.urls import path
from . import views

app_name = 'redaksi'

urlpatterns =[
    path('masuk/',views.index, name='index'),
    path('adminpage/',views.admin, name='adminpage'),
    path('staff/', views.staff, name='staff'),
    path('login_view',views.login_view, name='login_view'),
    path('register/',views.register, name='register'),
    path('',views.TampilWeb.as_view(),name='beranda'),
    path('tambah/',views.TambahWeb.as_view(),name='tambah'),
    path('baca/<slug:slug>/',views.DetailWeb.as_view(),name='detail'),
    path('edit/<pk>/',views.UpdateWeb.as_view(),name='ubah'),
    path('delete/<pk>/',views.DeleteWeb.as_view(),name='hapus'),
    path('like_post/',views.like_post, name='like_post'),
    path('view_blogs/',views.view_blogs,name='view_blogs'),
]

proyek/proyek/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

proyek/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.
class User(AbstractUser):
    admin = models.BooleanField('Admin',default=False)
    staff = models.BooleanField('Staff',default=False)

class IndexWeb(models.Model):
    judul = models.CharField(max_length=50)
    gambar = models.ImageField(upload_to='redaksi')
    paragraf = models.TextField()
    penulis = models.CharField(max_length=50)
    kategori = models.CharField(max_length=50)
    tanggal = models.DateField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, max_length=60, blank=True)

    class Meta:
        ordering =['-id']
    
    def __str__(self):
        return self.judul

proyek/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User 

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form_control'
            }
        )
    )
    password = forms.CharField(
        widget= forms.PasswordInput(
            attrs= {
                'class':'form_control'
            }
        )
    )

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form_control'
            }
        )
    )
    password1 = forms.CharField(
        widget= forms.PasswordInput(
            attrs= {
                'class':'form_control'
            }
        )
    )
    password2 = forms.CharField(
        widget= forms.PasswordInput(
            attrs= {
                'class':'form_control'
            }
        )
    )
    email = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form_control'
            }
        )
    )

    class Meta:
        model = User
        fields= ('username','password1','password2','email','admin','staff')

proyek/blog/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, LoginForm
from django.contrib.auth import authenticate, login
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from .models import IndexWeb
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse

# Create your views here.
def index(request):
    return render(request,'index.html')

def register(request):
    msg = None
    if request.method == 'POST':
        form = SignUpForm (request.POST)
        if form.is_valid():
            user = form.save()
            msg = 'User dibuat'
            return redirect('index')
        else:
            msg = 'form tidak valid'
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form':form,'msg':msg})

def login_view(request):
    form = LoginForm (request.POST or None)
    msg =None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None and user.admin:
                login(request,user)
                return redirect('redaksi:adminpage')
            elif user is not None and user.staff:
                login(request,user)
                return redirect('redaksi:staff')
            else:
                msg ='invalid credentials'
        else:
            msg='error validating form'
    return render(request, 'login.html', {'form':form,'msg':msg})

def admin(request):
    return render(request, 'admin.html')
def staff(request):
    data_webs = IndexWeb.objects.all()
    return render(request, 'staff.html',{'object_list':data_webs})

class TampilWeb(ListView):
    queryset = IndexWeb.objects.all()
class TambahWeb(CreateView):
    model = IndexWeb
    fields = '__all__'
    success_url = reverse_lazy('redaksi:beranda')
class DetailWeb(DetailView):
    model = IndexWeb
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
class UpdateWeb(UpdateView):
    model = IndexWeb
    fields = '__all__'
    success_url = reverse_lazy('redaksi:beranda')
class DeleteWeb(DeleteView):
    model =IndexWeb
    fields='__all__'
    success_url = reverse_lazy('redaksi:beranda')

def like_post(request):
    post_id = request.GET.get('post_id')
    try:
        post_id = int(post_id)
        post= IndexWeb.objects.get(pk=post_id)
        post.likes += 1
        post.save()
        return JsonResponse({'success':True,'likes':post.likes})
    except IndexWeb.DoesNotExist:
        return JsonResponse({'success':False,'error':'Post not found'})
    
def view_blogs(request):
    view_id = request.GET.get('view_id')
    try:
        view_id = int(view_id)
        blogs = IndexWeb.objects.get(pk=view_id)
        blogs.views += 1
        blogs.save()
        return JsonResponse({'success':True,'views':blogs.views})
    except IndexWeb.DoesNotExist:
        return JsonResponse({'success':False,'error':'Blog not found'})

proyek/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin</title>
</head>
<body>
    
</body>
</html>

proyek/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

proyek/templates/blog/indexweb_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hapus</title>
</head>
<body>
    <p>Apa anda yakin ingin mengahpus {{object.judul}}?</p>
    <p>Semua data yang terkait {{object.judul}} akan dihapus permanen</p>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit">Hapus</button>
    </form>
</body>
</html>

proyek/templates/blog/indexweb_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ikon/fontawesome-free-6.4.2-web/css/all.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>Baca</title>
</head>
<style>
    .liked{
        color: red;
    }
</style>
<body>
    <a class="ml-3 bg-blue-400 p-1 text-white rounded" href="{% url 'redaksi:beranda' %}">Kembali</a>
    <ul>
        <li><img class="mx-auto" src="{{object.gambar.url}}" alt="" width="300px" height="300px"></li>
        <li class="text-center font-bold">{{object.judul}}</li>
        <ul class="subjudul flex justify-evenly mb-10 mt-5">
            <li>
                <i class="fas fa-user"></i>
                {{object.penulis}}
            </li>
            <li>
                <i class="fas fa-newspaper"></i>
                {{object.kategori}}
            </li>
            <ul class="flex">
                <li><i class="fas fa-heart"></i></li>
                <li><div class="like font-bold">{{object.likes}}</div></li>
                <li><p>Likes</p></li>
            </ul>
        </ul>
        <li class="ml-3 mr-3">{{object.paragraf}}</li>
        
        {% for redaksi in object_list %}
        {{redaksi.judul}}
        {% endfor %}
    </ul>
    <script>
        const likeIkon= document.querySelector('.fa-heart');
        const hasilLike = document.querySelector('.like');
        let count = 0;

likeIkon.addEventListener('click',function(){

    const postID = "{{object.id}}";

    fetch(`/like_post/?post_id=${postID}`)
    .then(response => response.json())
    .then(data => {
            if (data.success) {
                if(likeIkon.classList.contains('liked')){
                    likeIkon.classList.remove('liked');
                    count = 0;
                } else{
                    likeIkon.classList.add('liked');
                    count = data.likes;
                }

                hasilLike.innerHTML= count;
            } else{
                console.error('gagal like post:',data.error);
            }
        })
        .catch(error =>{
        console.error('Error liking post:',error);
        });
    });
    
    </script>
</body>
</html>
{% endblock %}

proyek/templates/blog/indexweb_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>form</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Simpan">
    </form>
</body>
</html>

proyek/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Beranda</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'redaksi:login_view' %}">Login</a></li>
        <li><a href="{% url 'redaksi:register' %}">register</a></li>
    </ul>
</body>
</html>

proyek/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Kirim">
    </form>
</body>
</html>

proyek/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>register</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Kirim">
    </form>
</body>
</html>